name: Continuous integration with GitHub Actions

on:
  push:
    branches: 
      - main 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application jat
      working-directory: ./rest-with-spring-boot-and-java-samuca
      run: mvn clean package
      
    - name: Docker compose Build 
      working-directory: ./
      run: docker compose build
      
    - name: Push to Docker Hub container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-samuca:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-samuca:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-samuca:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-samuca:latest
